# Experimental: Pixi.sh  {.unnumbered}

Pixi is a fast, modern, and reproducible package management tool for developers of all backgrounds.

[https://pixi.sh/latest/](https://pixi.sh/)

## Installation

[https://pixi.sh/latest/installation/](https://pixi.sh/latest/installation/)

To install pixi you can run the following command in your terminal:

### Linux & macOS

```bash
curl -fsSL https://pixi.sh/install.sh | sh
```

If your system doesn't have curl, you can use wget:

```bash
wget -qO- https://pixi.sh/install.sh | sh
```

What does this do?

The above invocation will automatically download the latest version of pixi, extract it, and move the pixi binary to `~/.pixi/bin`. The script will also extend the `PATH` environment variable in the startup script of your shell to include `~/.pixi/bin`. This allows you to invoke pixi from anywhere.

Now restart your terminal or shell to make the installation effective.

### Windows

Download the MSI installer: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-pc-windows-msvc.msi

**OR:**

Or run:

```
powershell -ExecutionPolicy ByPass -c "irm -useb https://pixi.sh/install.ps1 | iex"
```

What does this do?

The above invocation will automatically download the latest version of pixi, extract it, and move the pixi binary to `%UserProfile%\.pixi\bin`. The command will also add `%UserProfile%\.pixi\bin` to your `PATH` environment variable, allowing you to invoke pixi from anywhere.
Now restart your terminal or shell to make the installation effective.

## Installing packages and running commands

For more backround, please read the manual:
<https://pixi.sh/latest/getting_started/>

From here you would use `pixi` for
installing additional packages or creating environments with an
environment.yml file.

The next step is creating environments and install
packages into into your folder-based flexible Python
working environment. For here you should know what you are doing, as this is different from 
the micromamba/conda approach documented for this workshop.

Check out the [4. Creating environments and install
packages](04a_Creating_environments.html) page to see which packages are needed.

Then, set up the JupyterLab notenook environment with Pixi. 

- [https://pixi.sh/latest/integration/editor/jupyterlab/](https://pixi.sh/latest/integration/editor/jupyterlab/)

Check out the [5. Setting up Jupyter Notebook](05_setup_jupyter.html) page to see for the Micromamba approach.